version: '3.4'
services:
  browsertests:
    environment:
      - BROWSER=${BROWSER:-chrome}
      - REMOTE=http://${SELENIUM_HOSTNAME:-seleniumbrowser}:4444/wd/hub
      - REMOTE_STATUS=http://${SELENIUM_HOSTNAME:-seleniumbrowser}:4444/wd/hub/status
    command: ./script/runtests
    depends_on:
      - seleniumbrowser

  seleniumbrowser:
    image: ${SELENIUM_IMAGE:-selenium/standalone-chrome:latest}
    container_name: ${SELENIUM_HOSTNAME:-seleniumbrowser}
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
      - "7900:7900"
    healthcheck:
      test: ["CMD-SHELL", '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444']
      interval: 15s
      timeout: 30s
      retries: 5
