services:
  browsertests:
    environment:
      - BROWSER=${BROWSER:-chrome}
      - HEADLESS
      - REMOTE=http://${SELENIUM_HOSTNAME:-seleniumbrowser}:4444/wd/hub
      - WAIT_ON_ENDPOINT=${WAIT_ON_ENDPOINT:-http://seleniumbrowser:4444/wd/hub/status}
    depends_on:
      - seleniumbrowser

  seleniumbrowser:
    # The selenium/standalone-chromium image is multiplatform (arm64)
    image: ${SELENIUM_IMAGE:-selenium/standalone-chromium:latest}
    platform: ${SELENIUM_IMAGE_PLATFORM:-}
    container_name: ${SELENIUM_HOSTNAME:-seleniumbrowser}
    # shm size should be considered with parallelism
    shm_size: 4gb
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "5900:5900"
      - "7900:7900"
    environment:
      # The number of browser sessions should correspond to parallelism
      - SE_NODE_MAX_SESSIONS=2
    healthcheck:
      test: ["CMD-SHELL", '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444']
      interval: 15s
      timeout: 30s
      retries: 5
