version: '3.4'
services:
  browsertests:
    build: .
    container_name: ${BROWSERTESTS_HOSTNAME:-browsertests}
    volumes:
      - .:/app
    environment:
      - LOGIN_USERNAME
      - LOGIN_PASSWORD
