version: '3.4'
services:
  browsertests:
    environment:
      - BROWSER=firefox
      - REMOTE=http://seleniumfirefox:4444/wd/hub
    command: ./script/runtests
    depends_on:
      - seleniumfirefox

  seleniumfirefox:
    image: selenium/standalone-firefox:latest
    container_name: selenium-firefox
    shm_size: 2gb
    volumes:
      - /dev/shm:/dev/shm
    healthcheck:
      test: ["CMD-SHELL", '/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444']
      interval: 15s
      timeout: 30s
      retries: 5
