#!/bin/sh

# Exit script on any errors
set -e

# Run RuboCop in the bundle environment for linting
# and pass through any arguments
run_command="bundle exec rubocop $@"

# Generic run command and catch error
echo "RUNNING [${run_command} ]..."
# Allow to fail but catch return code
set +e
$run_command
run_return_code=$?
# NOTE return code must be caught before any other command
set -e
echo ''

echo "EXITING WITH RUN RETURN CODE [${run_return_code}]"
exit $run_return_code
