#!/bin/sh

# Exit script on any errors
set -e

# Run bundler-audit in the bundle environment for
# security scan of dependencies and pass through
# any arguments
run_command="bundle exec bundle-audit check --update $@"

# Generic run command and catch error
echo "RUNNING [${run_command}]..."
# Allow to fail but catch return code
set +e
$run_command
run_return_code=$?
# NOTE return code must be caught before any other command
set -e
echo ''

echo "EXITING WITH RUN RETURN CODE [${run_return_code}]"
exit $run_return_code
