#!/bin/sh
# This script orchestrates running the browser tests
# with a remote browser if it's status point is set

# Assumes wget (Alpine)

if [ ! -z "${REMOTE_STATUS}" ];
then
  COUNTER=0
  echo "Waiting for ${REMOTE_STATUS} to become available"
  until wget --spider -q "${REMOTE_STATUS}" &>/dev/null; do
    printf "."
    sleep 1
    COUNTER=$((COUNTER + 1))
    if [ $COUNTER -eq 30 ] ; then
      echo "✘"
      exit 1
    fi
  done

  echo "✔"
fi

# Run the tests (with any passed in args)
bundle exec cucumber "$@"
