name: Check Development Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  DEVENV: devenv
  IMAGE: app-devenv

jobs:
  build-devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build settings 
        run: "echo DOCKER_BUILDKIT=${DOCKER_BUILDKIT} --target ${DEVENV} -t ${IMAGE}" 

      - name: Build app development environment 
        run: "docker build --no-cache --target ${DEVENV} -t ${IMAGE} ." 

      - name: Check no mutation to source
        run: "[ ! -f foobear ]"

      - name: Mutate source in dev env
        run: docker run --rm -v ${PWD}:/app app-devenv touch foobear
 
      - name: Check source is mutated
        run: "[ -f foobear ]"

  runtests-default-firefox:
    needs: build-devenv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: Build app development environment 
        run: "docker build --no-cache --target ${DEVENV} -t ${IMAGE} ." 

      - name: docker-compose version
        run: docker-compose --version

      - name: docker-compose config
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumfirefox.yml config"

      - name: pull
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumfirefox.yml pull"

      - name: Run Selenium Firefox
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumfirefox.yml run -d seleniumfirefox"

      - name: Run Tests
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumfirefox.yml run browsertests"

  runtests-chrome:
    needs: build-devenv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: docker version
        run: docker --version

      - name: Build app development environment 
        run: "docker build --no-cache --target ${DEVENV} -t ${IMAGE} ." 

      - name: docker-compose version
        run: docker-compose --version

      - name: docker-compose config
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumchrome.yml config"

      - name: docker-compose pull
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumchrome.yml pull"

      - name: Run Selenium Chrome
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumchrome.yml run -d seleniumchrome"

      - name: Run Tests
        run: "SRC=${PWD} docker-compose -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.seleniumchrome.yml run browsertests"
