name: Check Development Environment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Use Docker Buildkit for builds
  DOCKER_BUILDKIT: 1
  DEVENV: devenv
  BROWSERTESTS_IMAGE: app-devenv

jobs:
  build-devenv:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker version
        run: docker --version

      - name: Build settings
        run: "echo DOCKER_BUILDKIT=${DOCKER_BUILDKIT} --target ${DEVENV} -t ${BROWSERTESTS_IMAGE}"

      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: Check no mutation to source
        run: "[ ! -f foobear ]"

      - name: Mutate source in dev env
        run: docker run --rm -v ${PWD}:/app app-devenv touch foobear

      - name: Check source is mutated
        run: "[ -f foobear ]"

  run-tests-default-chrome:
    needs: build-devenv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: dockercomposerun (Run tests) with defaults
        run: ./script/dockercomposerun

  runtests-specified-firefox:
    needs: build-devenv
    runs-on: ubuntu-latest
    env:
      BROWSER: firefox
      SELENIUM_IMAGE: selenium/standalone-firefox:latest

    steps:
      - uses: actions/checkout@v1
      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: dockercomposerun (Run tests) with Firefox
        run: ./script/dockercomposerun

  runtests-specified-edge:
    needs: build-devenv
    runs-on: ubuntu-latest
    env:
      BROWSER: edge
      SELENIUM_IMAGE: selenium/standalone-edge:latest

    steps:
      - uses: actions/checkout@v1
      - name: Build app development environment
        run: "docker build --no-cache --target ${DEVENV} -t ${BROWSERTESTS_IMAGE} ."

      - name: dockercomposerun (Run tests) with Edge
        run: ./script/dockercomposerun
