name: On PR Build Push Vet

on:
  pull_request:
    branches:
      - main

# FYI...
#  Raw Branch Name: ${{ github.head_ref }}
#  <commit-sha>: ${{ github.event.pull_request.head.sha }}

# Produced multi-architecture (linux/amd64,linux/arm64) images...
#  1. (Always) Unvetted Image: <owner/repository>_<normalized-branch>_unvetted:<commit-sha>
#  2. (Always) Dev Environment Image: <owner/repository>_<normalized-branch>_dev:<commit-sha>
#  3. (If vetted) Vetted_image: <owner/repository>_<normalized-branch>:<commit-sha>

jobs:
  # Normalize the branch for image name
  pr-norm-branch:
    uses: brianjbayer/actions-image-cicd/.github/workflows/normalize_for_image_name.yml@main
    with:
      raw_name: ${{ github.head_ref }}

  # Build and Push Images
  buildx-and-push-branch-devenv:
    needs: [pr-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/buildx_push_image.yml@main
    with:
      image: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_dev:${{ github.event.pull_request.head.sha }}
      platforms: "linux/amd64,linux/arm64"
      buildopts: --target devenv
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  buildx-and-push-branch-unvetted:
    needs: [pr-norm-branch]
    uses: brianjbayer/actions-image-cicd/.github/workflows/buildx_push_image.yml@main
    with:
      image: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_unvetted:${{ github.event.pull_request.head.sha }}
      platforms: "linux/amd64,linux/arm64"
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # Vet Deploy Image
  vet-code-standards:
    needs: [pr-norm-branch, buildx-and-push-branch-devenv]
    runs-on: ubuntu-latest
    env:
      DEVENV_IMAGE: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_dev:${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v1
      - name: dockercomposerun rubocop on development environment
        run: "BROWSERTESTS_IMAGE=${DEVENV_IMAGE} ./script/dockercomposerun -n -d ./script/run lint"

  vet-dependency-security:
    needs: [pr-norm-branch, buildx-and-push-branch-devenv]
    runs-on: ubuntu-latest
    env:
      DEVENV_IMAGE: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_dev:${{ github.event.pull_request.head.sha }}
    steps:
      - uses: actions/checkout@v1
      - name: dockercomposerun bundle-audit on development environment
        run: "BROWSERTESTS_IMAGE=${DEVENV_IMAGE} ./script/dockercomposerun -n -d ./script/run secscan"

  vet-deploy-e2e-tests-matrix:
    needs: [pr-norm-branch, buildx-and-push-branch-unvetted]
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    runs-on: ubuntu-latest
    env:
      UNVETTED_IMAGE: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_unvetted:${{ github.event.pull_request.head.sha }}
      BROWSER: ${{ matrix.browser }}
      SELENIUM_IMAGE: selenium/standalone-${{ matrix.browser }}:latest
      BASE_URL: "https://the-internet.herokuapp.com"
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: dockercomposerun unvetted image
        run: "BROWSERTESTS_IMAGE=${UNVETTED_IMAGE} ./script/dockercomposerun -c"

# Copy (IF) Vetted Deploy Image
  copy-branch-vetted-deploy-image:
    needs:
      - vet-code-standards
      - vet-dependency-security
      - vet-deploy-e2e-tests-matrix
      - pr-norm-branch
    uses: brianjbayer/actions-image-cicd/.github/workflows/copy_image.yml@main
    with:
      source_image: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_unvetted:${{ github.event.pull_request.head.sha }}
      target_image: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}:${{ github.event.pull_request.head.sha }}
    secrets:
      registry_u: ${{ secrets.DOCKER_HUB_USERNAME }}
      registry_p: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  # Vet Dev Environment Image
  vet-devenv-e2e-tests-matrix:
    needs: [pr-norm-branch, buildx-and-push-branch-devenv]
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox, edge]
    runs-on: ubuntu-latest
    env:
      DEVENV_IMAGE: ${{ github.repository }}_${{ needs.pr-norm-branch.outputs.name }}_dev:${{ github.event.pull_request.head.sha }}
      BROWSER: ${{ matrix.browser }}
      SELENIUM_IMAGE: selenium/standalone-${{ matrix.browser }}:latest
      BASE_URL: "https://the-internet.herokuapp.com"
      LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
      LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: dockercomposerun devenv image
        run: "BROWSERTESTS_IMAGE=${DEVENV_IMAGE} ./script/dockercomposerun -d ./script/run tests"
